var a = true && false; 
    console.log(a);
var b = true || false; 
    console.log(b);
var c = false && false;
    console.log(c);
var d = true && (false || true);
    console.log(d);
var e =false || (true && false);
    console.log(e);
var f = (false | 1< 5);
    console.log(f);
var g = 5 >= 4 && 1 > 3;
    console.log(g);
var h = 10 < 4 || 1> 4
    console.log(h);
var i = 12 >= 2 && 1 < 24;
    console.log(i);
var j = 'Hello'.charAt(0) == 'h';
    console.log(j);